Repository pasinduChinthana/gpa_calculator, pull requests merged in 2021-10, with the labels that each got.

#8 configure Grade Points screen
  lib/screens/configure_grade_points_screen.dart
  lib/screens/create_profile_screen.dart
Labels: enhancement, hacktoberfest-accepted

#9 Update
  CONTRIBUTING.md
  README.md
  lib/components/profile_selector.dart
  lib/main.dart
  lib/screens/configure_grade_points_screen.dart
  lib/screens/create_profile_screen.dart
  lib/screens/home_screen.dart
  test123
Labels: enhancement, hacktoberfest-accepted

#10 Development
  README.md
Labels: enhancement, hacktoberfest-accepted

#14 Updated readme - FAQs
  README.md
Labels: documentation, hacktoberfest-accepted

#15 Update
  README.md
Labels: hacktoberfest-accepted

#16 Development
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted
